language: go

go:
  - 1.9.x

before_install:
  - go get -u github.com/golang/lint/golint

script:
  - make test

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: false
